auth:
  enabled: true
  cognito:
    enabled: true
    logoutUrl:
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
      client:
        registration:
          cognito:
            client-id:
            client-secret:
            scope:
            redirect-uri:
            client-name:
        provider:
          cognito:
            issuerUri:
            user-name-attribute:
